name: CI

on:
  pull_request:
    branches:
      - prod
      - staging
      - dev
  push:
    branches:
      - feat/*
      - fix/*
      - chore/*

env:
  BRANCH_NAME: ${{github.ref_name}}
  WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL_TRACKER}}

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      # IS A PUSH
      - if: contains(fromJson('["push"]'), github.event_name)
        uses: rtCamp/action-slack-notify
        env:
          SLACK_CHANNEL: develop_tracker
          SLACK_TITLE: Heyy! We've new push üöÄüöÄüöÄ
          SLACK_USERNAME: (CI) Tracker
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL_TRACKER}}
          SLACK_MESSAGE: Changes into ${{env.BRANCH_NAME}}

      # IS A PULL REQUEST
      - if: contains(fromJson('["pull_request"]'), github.event_name)
        uses: rtCamp/action-slack-notify
        env:
          SLACK_CHANNEL: code_review
          SLACK_TITLE: Heyy! We've news from a pull request ‚ö†Ô∏è‚ö†Ô∏è‚ö†Ô∏è
          SLACK_USERNAME: (CI) Tracker
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL_TRACKER}}
          SLACK_MESSAGE: PR into ${{env.BRANCH_NAME}}

  # build:
  #   # if: contains(fromJson('["pull_request"]'), github.event_name)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout to the repository
  #       uses: actions/checkout@v2

  #     - name: Set up NodeJS environment
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 18

  #     - name: Cache node modules
  #       id: cache-npm
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: cache-node-modules
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-build-${{ env.cache-name }}-
  #           ${{ runner.os }}-build-
  #           ${{ runner.os }}-

  #     - name: Install package dependencies
  #       run: npm install

  #     - name: Create test build
  #       run: npm run build
